#Properties
gson.version=2.10.1
java.version=21.0.3
keycloak.version=26.3.3
maven.compiler.source=21
maven.compiler.target=21
project.build.sourceEncoding=UTF-8
resteasy.version=3.12.0
version.compiler.maven.plugin=3.8.1
